### ISSUE TITLE
Uncaught TypeError: fileTools.bindNotifications is not a function (line 16)

### ISSUE THREAD

**Issue by bdee1** [RyanSiu1995/ckeditor-ImageUploader#1]
I am getting the following error when I try to upload a file:
Uncaught TypeError: fileTools.bindNotifications is not a function on line 16 of plugin.js.

can you assist please?

**Comment by life-jin** [comment]
me too 
plugin.js:18 Uncaught TypeError: fileTools.bindNotifications is not a function

**Comment by life-jin** [comment]
im solved add this plugins
notification,notificationaggregator,filetools,widget,uploadwidget,widgetselection,lineutils
but i have another problem this
Error code: filetools-response-error. {responseText: ""}

**Comment by life-jin** [comment]
im solved
{'uploaded':1, 'fileName':'a.jpg', 'url':'http://a.jpg'}

**Comment by RyanSiu1995** [comment]
Sorry for the late reply. I have a project to handle recently so I did not have time to answer the question. Thank for the reporting the bug. 
As life-jin mentioned, it should be the problem that there should be one more extra plugin for this plugin. It should be the filetools which can be downloaded at the following website.
[https://github.com/ckeditor/ckeditor-dev/tree/master/plugins/filetools](https://github.com/ckeditor/ckeditor-dev/tree/master/plugins/filetools)
Of course, you might be required to add all the plugin required in filetools.
I will add the dependency back to the documentation. Thank you for your supporting.
